In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
movies = pd.read_csv('./data/movies.tsv', sep = '\t')
movies_2 = pd.read_csv('./data/movies_2.tsv', sep = '\t')

C:\Users\Caleb\anaconda3\envs\dsi\lib\site-packages\IPython\core\interactiveshell.py:3072: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [7]:
ratings = pd.read_csv('./data/ratings.tsv', sep = '\t')

In [8]:
ratings

            tconst  averageRating  numVotes
0        tt0000001            5.6      1647
1        tt0000002            6.1       198
2        tt0000003            6.5      1347
3        tt0000004            6.2       120
4        tt0000005            6.1      2134
...            ...            ...       ...
1075219  tt9916580            7.2         5
1075220  tt9916690            6.6         5
1075221  tt9916720            5.8        60
1075222  tt9916766            6.9        14
1075223  tt9916778            7.3        24

[1075224 rows x 3 columns]

In [13]:
movies = movies.merge(right = movies_2, left_on = 'tconst', right_on = 'titleId')

In [17]:
movies = movies.merge(right = ratings, left_on = 'tconst', right_on = 'tconst')

In [19]:
movies = movies[movies['titleType'] == 'movie']
movies = movies[movies['region'] == 'US']

In [106]:
movies_pop = movies[(movies['numVotes'] > 5000)]

In [107]:
len(movies_pop.tconst.unique())

11874

In [ ]:
movies_pop

In [124]:
movies_2020 = movies_pop[movies_pop['startYear'] == '2003']

In [125]:
movies_2020.title.unique()

array(['Intolerable Cruelty', 'Intolerable', 'Cold Mountain',
       'Sinbad: Legend of the Seven Seas', 'The Return of the King',
       'The Lord of the Rings: The Return of the King', 'Bad Boys II',
       'Bad Boys 2', 'Bad Around the World', 'T3: Rise of the Machines',
       'Terminator 3', 'Terminator 3: Rise of the Machines', 'T3',
       'York Square', 'The Fighting Temptations', 'In the Cut',
       'Beyond Re-Animator', 'The Matrix 2',
       'The Matrix Reloaded: The IMAX Experience', 'The Burly Man',
       'The Matrix Reloaded', 'The Matrix 3', 'The Matrix Revolutions',
       'The Matrix Revolutions: The IMAX Experience',
       'The Sleeping Dictionary', 'Bulletproof Monk',
       'How to Lose a Guy in 10 Days', 'How to Lose a Guy',
       'House of 1,000 Corpses', 'House of 1000 Corpses', 'Found Someone',
       'S.W.A.T.', 'Kangaroo Jack', 'The Devil', 'Shortcut to Happiness',
       'Uptown Girls', 'Molly Gunn', 'View from the Top',
       'A View from the Top', 'Basic', 'El Diablo',
       'Untitled Vin Diesel Project', 'A Man Apart',
       "This Man's Dominion", 'Duplex', 'Finding Nemo', 'Finding Nemo 3D',
       'Kill Bill: Volume 1', "Quentin Tarantino's Kill Bill: Volume One",
       'Kill Bill: Vol. 1', 'Kill Bill', 'Kill Bill Part 1', 'Marci X',
       'The Hunted', 'The Guest', "My Boss's Daughter",
       'National Security', 'Johnny English',
       "The Film 'Dogville' as Told in Nine Chapters and a Prologue",
       'Ned Kelly', 'Gods and Generals', "Don't Peek", 'Tooth Fairy',
       'The Ghost of Matilda Dixon',
       'The Tooth Fairy: The Ghost of Matilda Dixon', 'Darkness Falls',
       'The Jungle Book 2', 'Dreamcatcher', 'Once Upon a Time in Mexico',
       'El Mariachi 3', 'The Triplets of Belleville', 'The Hulk', 'Hulk',
       'Big Green', 'American Girl', 'What a Girl Wants',
       'London Calling', 'Scorched', 'Daredevil: A Daring New Vision',
       'Daredevil', 'Highbinders', 'Young Adam', 'Fear X',
       'The Life of David Gale', 'X-Men 2: X-Men United', 'X-Men United',
       'X-2', 'X-Men 2', 'X-Men II', 'X2: X-Men United', 'X²', 'The Farm',
       'The Recruit', 'Beyond Borders', 'A Guy Thing', 'Wrong Turn',
       'Taxi 3', 'The Core', 'Core', 'All the Real Girls', 'Tough Love',
       'Gigli', 'I Capture the Castle', 'Shanghai Noon 2',
       'Shanghai Knights', 'Timeline', 'Deliver Us from Eva',
       'Good Bye Lenin!', 'Jeepers Creepers 2',
       'Like Hell: Jeepers Creepers 2',
       'Jeepers Creepers 2: The Second Night',
       'The United States of Leland', "National Lampoon's Barely Legal",
       'Barely Legal', 'Old School', 'Japanese Story', 'Levity',
       'Mona Lisa Smile', 'The Order', 'The Sin Eater',
       'American Splendor', 'Anger Management', "Charlie's Angels 2",
       "Charlie's Angels: Full Throttle", "Charlie's Angels: Halo",
       'In the Houze', 'Bringing Down the House', 'JailBabes.com',
       'Just Married', 'Scary Movie 3', 'Scary Movie 3.5',
       'Scary Movie 3: Episode I - Lord of the Brooms', 'Scary Movie III',
       'Cradle 2 the Grave', 'The Divorce', 'Le divorce',
       'The Lizzie McGuire Movie', 'Lizzie in Rome', 'Ciao Lizzie!',
       'Badder Santa', 'Bad Santa', 'Dead End', 'The Human Stain',
       'The Shape of Things', 'Down with Love', 'Final Destination 2',
       'I.D.', 'Identity', 'Luther', 'The Dreamers', 'Ruby & Quentin',
       'A Mighty Wind', 'Untitled Christopher Guest Project', 'Willard',
       'CONfidence', 'Confidence',
       'Master and Commander: The Far Side of the World',
       'The Far Side of the World', 'Holes', 'The League', 'LXG',
       'LXG: The League of Extraordinary Gentlemen',
       'The League of Extraordinary Gentlemen', 'Pieces of April',
       'The Cat in the Hat', "Dr. Seuss' The Cat in the Hat",
       'Chasing the Dragon: The Veronica Guerin Story', 'The Foreigner',
       'Out of Time', 'Runaway Jury', 'Anything Else',
       'Woody Allen Spring Project 2002', 'Agent Cody Banks',
       'Cody Banks', 'Love, Actually', 'Love Actually Is All Around',
       'Hostile Act', 'Rules of Engagement', 'Man of War',
       'Hostile Rescue', 'Tears of the Sun', 'My Life Without Me',
       'New Cardiff', 'The Singing Detective', 'The In-Laws',
       'The Wedding Party', 'Till Death Do Us Part', 'Bruce Almighty',
       '21 Grams', 'House of Sand and Fog', 'Open Range', 'Peter Pan',
       'Radio', 'Daddy Day Care', 'House of the Dead', 'The Italian Job',
       'The McNamara Project', 'The Fog of War',
       'The Fog of War: Eleven Lessons from the Life of Robert S. McNamara',
       'Looney Tunes: The Movie', 'Race Jam', 'Spy Jam',
       'Looney Tunes Back in Action: The Movie',
       'The Untitled Looney Tunes Project',
       'Loosely Based on a True Love Story', 'Alex & Emma', 'The Gambler',
       'The Cooler', 'Big Fish', 'Elf', 'How to Deal',
       "I'll Sleep When I'm Dead", 'Party Monster', 'Underworld',
       'The Fast and the Furious 2', '2 Fast 2 Furious', 'Freaky Friday',
       'Honey', 'Northfork', "Piglet's Big Movie", 'Shade',
       'Shattered Glass', 'Swimming Pool', 'Time of the Wolf',
       'The Texas Chainsaw Massacre', 'Ted and Sylvia',
       'Bright Young Things', 'Dickie Roberts: (Former) Child Star',
       'Dickie Roberts: Former Child Star', 'Head of State',
       'Tomb Raider 2', 'Lara Croft Tomb Raider: The Cradle of Life',
       'Samurai', 'The Last Samurai: Bushidou', 'The Last Samurai',
       'Matchstick Men', 'P.O.T.C.', 'Pirates of the Caribbean',
       'Pirates of the Caribbean: The Curse of the Black Pearl',
       'Stander', 'Biker Boyz', "I'm Not Scared", 'Mystic River',
       'Secondhand Lions', 'The Rundown', 'Helldorado',
       'Welcome to the Jungle', 'Call of the Wild', 'I Am David',
       "Malibu's Most Wanted", 'Suckaz', 'Thirteen',
       'Under the Tuscan Sun', 'American Pie 3', 'American Wedding',
       'American Pie 3: Piece of Pie', 'Bears', 'Tierra de osos',
       'Brother Bear', 'Dumb & Dumber 2',
       'Dumb and Dumberer: When Harry Met Lloyd', 'Dumb & Dumberer',
       'Dumber & Dumbest', 'When Harry Met Lloyd: Dumb and Dumberer',
       'A Nightmare on Elm Street 8: Freddy vs. Jason',
       'A Nightmare on Elm Street and Friday the 13th',
       'Freddy Versus Jason', 'Friday the 13th Part 11',
       'A Nightmare on Elm Street 8',
       'Friday the 13th Part XI: Freddy vs. Jason',
       'A Nightmare on Friday the 13th',
       'Freddy Krueger Versus Jason Voorhees',
       'Friday the 13th Part 11: Freddy vs. Jason',
       'Friday the 13th Part XI', 'FvJ', 'Monsieur Ibrahim', 'Seabiscuit',
       'Two Cops', 'Untitled Harrison Ford Starrer', 'Hollywood Homicide',
       'The Brown Bunny', "The Devil's Throat", 'Cold Creek Manor',
       '11:14', 'School of Rock', 'Legally Blonde 2', 'The Company',
       'Girl with a Pearl Earring', 'Lost in Translation',
       'The Wonderland Murders', 'Gardener', "Love Don't Co$t a Thing",
       'If You Were My Girl', "Can't Buy Me Love",
       "Love Don't Cost a Thing", 'The Rugrats Movie III',
       'Rugrats 3: Rescue Me', 'Rescue Me',
       'Rugrats Meet the Wild Thornberrys', 'Rugrats Go Wild',
       'The Snow Walker', 'Untitled Nancy Meyers Project',
       "Something's Gotta Give", 'Calendar Girls', 'Grind',
       'The Haunted Mansion', "Disney's The Haunted Mansion",
       'High Tension', 'The Barbarian Invasions', 'The Missing',
       'The Last Ride', 'Evil', 'Paycheck', 'Spy Kids 3: Game Over',
       'Spy Kids 3-D: Game Over', 'Spy Kids 3', 'Stuck on You',
       'Battle Royale II', 'From Justin to Kelly: With Love',
       'From Justin to Kelly',
       'From Justin to Kelly: A Tale of Two American Idols', 'The S.H.U.',
       'Hell', 'In Hell', 'Security Housing Unit', 'The Professional',
       'Undead', 'The Station Agent', 'Monster', 'Camp',
       'Capturing the Friedmans', 'Tupac: Resurrection', 'Code 46',
       'Latter Days', 'The Best of Youth', 'Going Going',
       'Tomorrow May Never Come', 'Gothika', 'Cheaper by the Dozen',
       'Nói', 'Facing Windows', 'Sky Blue', 'Memories of Murder',
       'De fem benspænd', 'Save the Green Planet!', 'Foolproof',
       'Yakuza Horror Theater: Gozu', 'Gozu',
       'National Lampoon Presents Dorm Daze',
       "National Lampoon's Dorm Daze", 'Dorm Day Crazy', 'Dorm Daze',
       'The Blind Swordsman: Zatoichi', 'Elephant', 'Love Me If You Dare',
       'Oldboy', 'A Tale of Two Sisters', 'One Missed Call',
       'The Saddest Music in the World', 'The Man Who Copied', 'Ju-on 2',
       'The Room',
       'Interstella 5555: The 5tory of the 5ecret 5tar 5ystem',
       'Ong-Bak: The Thai Warrior', 'Saints and Soldiers',
       'The Saints of War', 'Open Water', 'The Memory of a Killer',
       'Spring, Summer, Fall, Winter... and Spring',
       'Munna Bhai M.B.B.S.', 'The Return', 'Coffee and Cigarettes',
       'The Corporation', 'Favorite', 'Maqbool', 'Touching the Void',
       'The Yes Men', 'Tokyo Godfathers', 'Tarnation',
       'The Class of Chaos Goes Abroad'], dtype=object)

In [225]:
movies_df = pd.DataFrame(columns = ['id', 'titles', 'year', 'rating'])

count = 0

for movie_id in movies_pop.tconst.unique():
    mov = movies_pop[movies_pop['tconst'] == movie_id]
    titles = set(list(mov.primaryTitle.values) + list(mov.originalTitle.values) + list(mov.title.values))
    year = mov[:1]['startYear'].values[0]
    rating = mov[:1]['averageRating'].values[0]
    
    movies_df = movies_df.append({'id' : movie_id, 'titles' : titles, 'year' : year, 'rating' : rating}, ignore_index = True)
    
    count += 1
    
    if (count % 100 == 0):
        print(count)

100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800

In [226]:
movies_df.sort_values(by = 'rating', ascending = False).head(50)

,id,titles,year,rating
3584,tt0111161,"{Rita Hayworth and Shawshank Redemption, The S...",1994,9.3
1317,tt0068646,"{The Godfather, Mario Puzo's The Godfather}",1972,9.2
1430,tt0071562,"{Son of Godfather, The Second Godfather, Mario...",1974,9.0
11656,tt7738784,{Peranbu},2018,9.0
6714,tt0468569,"{Rory's First Kiss, The Dark Knight: The IMAX ...",2008,9.0
3564,tt0110912,"{Pulp Fiction, Black Mask}",1994,8.9
11048,tt5275892,{O.J.: Made in America},2016,8.9
3380,tt0108052,{Schindler's List},1993,8.9
4658,tt0167260,"{The Return of the King, The Lord of the Rings...",2003,8.9
625,tt0050083,"{12 Angry Men, Twelve Angry Men}",1957,8.9
9461,tt2170667,{Wheels},2014,8.8
4467,tt0137523,{Fight Club},1999,8.8
1007,tt0060196,"{The Good, the Bad and the Ugly, The Good, the...",1966,8.8
11274,tt6019206,{Kill Bill: The Whole Bloody Affair},2011,8.8
8927,tt1754109,{Les Misérables in Concert: The 25th Anniversary},2010,8.8
11209,tt5813916,"{Dag II, The Mountain II}",2016,8.8
9348,tt2077886,{The Phantom of the Opera at the Royal Albert ...,2011,8.8
8227,tt1375666,"{Inception, Inception: The IMAX Experience, Ol...",2010,8.8
4295,tt0120737,"{The Fellowship of the Ring, The Lord of the R...",2001,8.8
11716,tt8176054,{Pariyerum Perumal},2018,8.8
6299,tt0419781,{Graves End},2005,8.8
3482,tt0109830,"{Forrest Gump: The IMAX Experience, Forrest Gump}",1994,8.8
11704,tt8110330,"{The Helpless Heart, Dil Bechara}",2020,8.8
824,tt0056058,"{Harakiri, Seppuku}",1962,8.7
2879,tt0099685,"{Good Fellas, Wiseguy, Goodfellas, GoodFellas}",1990,8.7
4441,tt0133093,{The Matrix},1999,8.7
1796,tt0080684,"{Star Wars V: The Empire Strikes Back, Star Wa...",1980,8.7
5763,tt0358456,{Earthlings},2005,8.7
1500,tt0073486,{One Flew Over the Cuckoo's Nest},1975,8.7
5085,tt0252597,"{Kibar Feyzo, Polite Feyzo}",1978,8.7
11761,tt8503618,{Hamilton},2020,8.7
4659,tt0167261,"{The Two Towers, The Lord of the Rings: The Tw...",2002,8.7
11523,tt7060344,"{Raatchasan, Ratsasan}",2018,8.7
2287,tt0090015,{Shoah},1985,8.6
2182,tt0088178,{Stop Making Sense},1984,8.6
544,tt0047478,"{Seven Samurai, Shichinin no samurai, The Magn...",1954,8.6
11441,tt6751668,"{Parasite, Gisaengchung}",2019,8.6
5026,tt0245429,"{Miyazaki's Spirited Away, Sen to Chihiro no k...",2001,8.6
5509,tt0317248,"{City of God, Cidade de Deus}",2002,8.6
1629,tt0076759,"{La guerra de las estrellas, Star Wars: Episod...",1977,8.6
11512,tt7019842,{96},2018,8.6
580,tt0048473,"{Pather Panchali, Pather Panchali: Song of the...",1955,8.6
4331,tt0120815,{Saving Private Ryan},1998,8.6
3759,tt0114369,"{Seven, The Seven Deadly Sins, Se7en}",1995,8.6
3091,tt0102926,"{Silence of the Lambs, The Silence of the Lambs}",1991,8.6
3122,tt0103767,{Baraka},1992,8.6
10819,tt4640206,"{Sachin A Billion Dreams, Sachin, Sachin The F...",2017,8.6
317,tt0038650,"{Frank Capra's It's a Wonderful Life, The Grea...",1946,8.6
4279,tt0120689,"{Stephen King's The Green Mile, The Green Mile}",1999,8.6
1725,tt0079221,"{Gol Maal, Mayhem}",1979,8.6

In [227]:
movies_df['titles'].astype(str).str.contains('%').sum()

0

In [228]:
def set_to_str(strset):
    titles_string = ''
    while True:
        try:
            titles_string += strset.pop() + '%'
        except:
            break
    
    titles_string = titles_string[:-1]
    return titles_string

In [229]:
movies_df['titles'] = movies_df['titles'].apply(set_to_str)

In [230]:
movies_df['titles']

0        The Birth of a Nation%In the Clutches of the K...
1        Intolerance: A Sun-Play of the Ages%Intoleranc...
2                                            Shoulder Arms
3        Broken Blossoms%Broken Blossoms or The Yellow ...
4        The Cabinet of Dr. Caligari%Das Cabinet des Dr...
                               ...
11869                          Metri Shesh Va Nim%Just 6.5
11870                                     Falling Inn Love
11871                  Malang - Unleash the Madness%Malang
11872                                      Coffee & Kareem
11873                                               Kaithi
Name: titles, Length: 11874, dtype: object

In [231]:
movies_df

,id,titles,year,rating
0,tt0004972,The Birth of a Nation%In the Clutches of the K...,1915,6.3
1,tt0006864,Intolerance: A Sun-Play of the Ages%Intoleranc...,1916,7.7
2,tt0009611,Shoulder Arms,1918,7.3
3,tt0009968,Broken Blossoms%Broken Blossoms or The Yellow ...,1919,7.3
4,tt0010323,The Cabinet of Dr. Caligari%Das Cabinet des Dr...,1920,8.1
...,...,...,...,...
11869,tt9817070,Metri Shesh Va Nim%Just 6.5,2019,7.9
11870,tt9860728,Falling Inn Love,2019,5.6
11871,tt9877170,Malang - Unleash the Madness%Malang,2020,6.5
11872,tt9898858,Coffee & Kareem,2020,5.1
11873,tt9900782,Kaithi,2019,8.5

In [232]:
movies_df.to_csv('movies_data/movies.csv')